### ISSUE TITLE
Some errors with :Implement

### ISSUE THREAD

**Issue by Shatur** [d86leader/vim-cpp-helper#11]
Calling `:Implement` on any manually-written constructor results with the following error:
![изображение](https://user-images.githubusercontent.com/22453358/77488256-5832b500-6e3d-11ea-83a3-557d1672e386.png)

Also the first call `:Implement` on any function produce the following error (but implementation will be created):
![изображение](https://user-images.githubusercontent.com/22453358/77488306-7b5d6480-6e3d-11ea-970e-84e8c03107f5.png)

**Comment by maurges** [comment]
Oops, that was me messily moving stuff between branches. Fixed it by merging the stable development branch here: a961159d4e43baf4314984d9045c24b9210fdc47

**Comment by Shatur** [comment]
Thanks!
