### ISSUE TITLE
"static" keyword is not ignored for :Implement

### ISSUE THREAD

**Issue by Shatur** [d86leader/vim-cpp-helper#12]
The issue is similar to #10. For example the following deginition:
```cpp
static void functionExample();
```
will have the following implementation:
```cpp
static void ClassName::functionExample()
{
}
```
but expected without `static` keyword:
```cpp
void ClassName::functionExample()
{
}
```

**Comment by maurges** [comment]
Done: ec26799922ddb57372c8631b1e7506860cd76dec

**Comment by Shatur** [comment]
Thank you!
