### ISSUE TITLE
Respect class name instead of file name

### ISSUE THREAD

**Issue by Shatur** [d86leader/vim-cpp-helper#6]
Hi! Thank you for your plugin. It looks like your plugin uses filenames for generating implementation. Is it possible to parse real class name? In some projects class names can have different case or nested classes.

**Comment by maurges** [comment]
Hello, thanks for using my plugin! As of 8b825a1ddd200f3822430e40da4b7bf4e16ff6c1 I've rewritten the parsers. They should now correcly get a real classname, including nested classes. If you encounter a case where it fails or produces jibberish, please send me an example!

**Comment by Shatur** [comment]
Thank you a lot!
